refactor(sdk): typescript update
phantombuster/sdk pull request #10
Opened 2024-09-09 11:13 UTC by DamienLaf

## 📝 What is this PR

-   [Specs](https://phantombuster.atlassian.net/browse/BE-204)

This is a rewriting of the current `phantombuster-sdk` in typescript.

## 🗒 Notes

To keep the behavior unchanged, tests have been made on the previous code.

here is the coverage:
![image](https://github.com/user-attachments/assets/4b992937-247e-4a00-9d47-898eac20320a)

-   [ ] This change requires a documentation update
-   [x] This change requires a unit tests update

2024-09-11 08:02 UTC, ghermet approved these changes

2024-09-12 15:02 UTC, Drax35c2db requested changes

2024-09-12 15:02 UTC, Drax35c2db commented on package.json
> +		"test": "echo \"Error: no tests exist\" && exit 1",
Please update the `test` command

2024-09-12 15:02 UTC, Drax35c2db commented on src/types.ts
> +>
Can we have a comment on the necessity of the record string string cast plz ? :)

2024-09-12 15:02 UTC, Drax35c2db commented on package.json
> +		"eslint-plugin-diff": "^2.0.3",
remove ?

2024-09-12 15:02 UTC, Drax35c2db commented on src/constants.ts
> +export const extentionRegexp = /.[^.]+$/
```suggestion
export const extensionRegexp = /\.[^.]+$/
```

2024-09-12 15:02 UTC, Drax35c2db commented on src/sdk.test.ts
> +		it("should not log if script does not exists bis", async () => {
```suggestion
		it("should not log if script does not exists", async () => {
```

2024-09-12 15:02 UTC, Drax35c2db commented on src/Logger.ts
> +		const label = realPath.endsWith(".json") || realPath.endsWith(".md") ? "[API store settings] " : ""
Maybe Put json and md logic outside of here ?

2024-09-16 13:02 UTC, Hatscat commented on package.json
> +	"version": "0.4.0",
Even if there is no behavior change, the deps are different, the built code is different and the package "scripts" are different. WDYT?
```suggestion
	"version": "0.4.1",
```

2024-09-23 13:16 UTC, DamienLaf commented on package.json
> +	"version": "0.4.0",
I think it should be the v1.0, but I wait for @Drax35c2db to tell me how I should bump the version and upgrade the package

2024-09-24 12:16 UTC, Drax35c2db approved these changes
LGTM

> I think it should be the v1.0, but I wait for @Drax35c2db to tell me how I should bump the version and upgrade the package

Let's validate this version with @paps first and then we can make more official next steps like npm versions bump

2024-10-16 07:33 UTC, merged