chore: upgrade `is-my-json-valid` to latest (`2.20.6`)
phantombuster/sdk pull request #8
Opened 2024-08-30 14:57 UTC by lamabiker

## 📝 What is this PR

There's a dependency in the SDK that's a security risk (https://github.com/phantombuster/phantom-store/security/dependabot/2)

This updates that package.

## 👌 To check

-   [ ] There's no regression
-   [ ] Coding guidelines are followed ([Contributing](https://github.com/phantombuster/engineering-docs/blob/master/contributing.md), [Testing](https://github.com/phantombuster/engineering-docs/blob/master/testing.md))

## 🚀 What to do after deployment

**Who should be notified after the deployment of this PR? What should be written in the changelog on Slack?**

2024-09-09 08:23 UTC, DamienLaf requested changes
You should run `npm i` after bumping the version to update the `package-lock.json` file.
You also changed the npm version that is in use.

2024-09-09 09:43 UTC, arnauddrain requested changes

2024-09-09 09:43 UTC, arnauddrain commented on README.md
Since this is not related to the is-my-json-valid update, it should be in a separate PR, probably with the prefix style

2024-09-09 09:43 UTC, arnauddrain commented on README.md
> +```
This is a public repository, primary readers of this doc will be users of the SDK, not developers of the repo. This should either be in a separate file, or in a specific section for developers of the project.
I also submitted [a PR with a simpler suggestion for this issue](https://github.com/phantombuster/sdk/pull/9).

2024-09-16 08:21 UTC, lamabiker commented
Closing in favour of https://github.com/phantombuster/sdk/pull/10

2024-09-16 08:21 UTC, closed without merging